### ISSUE TITLE
Questions about the effects when using larger batch size

### ISSUE THREAD

**Issue by Fantabulous-J** [starsuzi/DAR#1]
Hi,

Thanks for sharing your amazing work. I noticed that in your paper, the batch size is only 32 due to limited computing resources, while the official implementation of DPR uses 128. I am wondering if the mixup and dropout mask data augmentation strategies will still bring benefits when batch size increases.

**Comment by starsuzi** [comment]
Hello,

Thanks for your question.

Unfortunately, we do not have sufficient environments for training our model in the large batch size, thus we cannot directly estimate the results when we increase the batch size larger. But, we strongly believe that our method would be still powerful under the large batch size.
