### ISSUE TITLE
experimental result

### ISSUE THREAD

**Issue by tangjiawei777** [starsuzi/DAR#2]
hi,brother,why your experiment result not like the original DPR model showed?
you can see ,that's you dpr result:

![image](https://user-images.githubusercontent.com/72731422/189353561-1d55c2d3-d708-4346-a326-8815f9fb82df.png)

And that's original DPR model showing in github

![image](https://user-images.githubusercontent.com/72731422/189353793-42588563-2e8b-4576-96b0-79720a4bd830.png)

**Comment by starsuzi** [comment]
Hello,

Thanks for asking a question.

Please note that the experimental (hyper-)parameters (e.g., batch size) are slightly different from the original DPR paper,
as explained in the Implementation Details section.

However, as the DPR paper also provides the results of different batch sizes on the development set, 
we further compare the reported top-k accuracy and ours with the same batch size in Table 8.
The result shows that our reproduction is similar to the reported results, 
and please refer to Section B.2 in the Appendix for a more detailed explanation.
