### ISSUE TITLE
ablation experiment

### ISSUE THREAD

**Issue by tangjiawei777** [starsuzi/DAR#3]
hello,I want to know which py file could be run to get the ablation experiment result?

**Comment by starsuzi** [comment]
Hi,

Thanks for asking a question.
For the ablation experiments, please refer to the [biencoder_local.yaml](https://github.com/starsuzi/DAR/blob/cb426ef983df27bcfe72727f1136b89408fea779/conf/train/biencoder_local.yaml#L29-L33) file.
