### ISSUE TITLE
where is MAP and MRR in retrieval ?

### ISSUE THREAD

**Issue by tangjiawei777** [starsuzi/DAR#4]
hello ,when I run the 2_dense_retrieval.sh ,I can only get the top-k ,so  I  want to know how to get the value of MAP and MRR?

**Comment by starsuzi** [comment]
Hello,

Thanks for asking a question.

We have implemented MAP and MRR based on the open repositories, such as
https://gist.github.com/bwhite/3726239 and https://github.com/ncoop57/cute_ranking.

**Comment by tangjiawei777** [comment]
hi,bro.I tried the method you provided, but I didn't succeed. Can you provide a complete dense_retriever.py to me? thanks
